### ISSUE TITLE
Goes straight to search

### ISSUE THREAD

**Issue by BPontevorvo** [caleb531/youversion-suggest-alfred#23] opened 2023-03-25 09:31 UTC
Hey Caleb!

It's been two years since I reached out last. You were super helpful the first time and I use this workflow every single day. Thanks for making something so great. I am using Alfred 5. Once I type paste YVSearch or YVFilter, the next text goes straight to a google search. because of that, it doesn't work at all. I am on MacOS 13.2. I will attach a screenshot below. 

Thanks again! 
<img width="885" alt="Screenshot 2023-03-25 at 5 30 41 AM" src="https://user-images.githubusercontent.com/72838123/227709068-15fb9797-7807-454e-a3f2-3ea67e621e98.png">

<img width="806" alt="Screenshot 2023-03-25 at 5 30 49 AM" src="https://user-images.githubusercontent.com/72838123/227709037-8ce58724-bc69-4cda-bf35-d2ffae82857d.png">

**Comment by bevanjkay** [comment] 2023-03-25 10:58
@BPontevorvo This is a duplicate of issue #21 - @caleb531 Provided a fix as below;

> 
> It's because Apple's Command Line Tools need to be updated. Open a Terminal and run the following command:
> 
> `xcode-select --install`
> 
> It will prompt you to download and install the Command Line Tools for Ventura. Once it's finished downloading and installing, you should be set. No restart should be required, either.

**Comment by BPontevorvo** [comment] 2023-03-25 12:41
@bevanjkay That fixed part of it! Thank you.

Now I have an issue where a search that should return a value is not. Picture below!

![Screenshot 2023-03-25 at 8 41 23 AM](https://user-images.githubusercontent.com/72838123/227717877-66cb37e6-c41d-41fe-a011-4b48d9d015ed.png)

**Comment by caleb531** [comment] 2023-03-25 17:27
When your Bible workflow can't find "Jesus", you know you have a serious problem. 😂😅

## Re: the Apple Command Line Tools issue

This has been a common issue I plan to introduce an auto-install mechanism in the next release of YVS so you won't need to worry about this for future OS upgrades (provided you update to that YVS version when it's released).

## Search Issue

Short answer: I am able to reproduce this bug, but am going to create a separate GitHub issue to track it (for the sake of keeping things tidy). I will mention you in the new issue so you can follow along.

Closing this issue since the original Apple CLI Tools matter is resolved.

**Closed** 2023-03-25 17:28 UTC
Labels: duplicate

**Comment by caleb531** [comment] 2023-03-27 00:01
@BPontevorvo Just wanted to let you know that I posted a beta version of the workflow with the 'No Results' fix, and it should be quite usable if you want to give it a go:
https://github.com/caleb531/youversion-suggest-alfred/issues/24#issuecomment-1484278993
